version: '3.8'

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: always
    ports:
      - 8080:8080 # AIO interface (reverse proxy)
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
    environment:
      - NEXTCLOUD_DATADIR=/mnt/ncdata
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=supersecret
      - APACHE_PORT=11000 # avoid conflict with other services
      - APACHE_IP_BINDING=0.0.0.0

volumes:
  nextcloud_aio_mastercontainer:
