# local-only
version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strong_root_pw
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: strong_db_pw

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    command: redis-server --requirepass strong_redis_pw
    volumes:
      - redis:/data

  app:
    image: nextcloud:28-apache
    container_name: nextcloud-app
    restart: always
    ports:
      - 8080:80  # Accessible at http://localhost:8080
    volumes:
      - nextcloud:/var/www/html
    environment:
      MYSQL_PASSWORD: strong_db_pw
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: strong_redis_pw
    depends_on:
      - db
      - redis

volumes:
  db:
  redis:
  nextcloud:
